name: Build and Push Docker Image
on:
  push:
    branches:
      - main # ajuste para o nome da sua branch principal

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t docker.pkg.github.com/${{ github.repository }}/golang-queue-consumer:latest .
          docker push docker.pkg.github.com/${{ github.repository }}/golang-queue-consumer:latest
